version: '{build}'
configuration: Release
platform: Any CPU
install:
- cmd: choco install gitversion.portable -pre -y
before_build:
- ps: >-
    gitversion /l console /output buildserver /updateAssemblyInfo

    Update-AppveyorBuild -Version "$env:GitVersion_FullSemVer"


    nuget restore
build:
  verbosity: minimal